export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SCCESS="REGISTER_SCCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SCCESS="LOGIN_SCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"


export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SCCESS="GET_USER_SCCESS"
export const GET_USER_SCCESS_FAILURE="GET_USER_SCCESS_FAILURE"

export const LOGOUT="LOGOUT"

